from crewai import Task
from agents import promptTester


def testing_task(user_input: str):
    return Task(
        description=(
            f"Take all the generated prompts and test them using the user-provided input: '{user_input}'. "
            "Capture the result of each test case clearly and separately."
        ),
        expected_output="A list of outputs generated by each prompt variant using the given input.",
        agent=promptTester
    )