from crewai import Task

def testing_task(agent):
    return Task(
        description=(
            "Take all the generated prompts and test them using the user-provided input: '{user_input}'. "
            "Capture the result of each test case clearly and separately."
        ),
        expected_output="A list of outputs generated by each prompt variant using the given input.",
        agent=agent
    )
