from crewai import Agent
from llm.local_llm import llama3_llm # If you don't have api key, use this llm.
# from llm.cloud_llm import llm       "If you have api key, use this."

def promptEvaluator():
    return Agent(
        role="Prompt Evaluator",
        goal="Evaluate outputs from each prompt based on clarity, relevance, and effectiveness",
        backstory=(
        "You are an LLM prompt evaluator. You review outputs generated by each prompt variation "
        "and score them based on how well they achieve the original task."
        ),
        verbose=True,
        allow_delegation=False,
        llm=llama3_llm # or llm=llm
    )